import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)  #Board GPIO Pin numbers

GPIO2_FLOW_METER = 13
GPIO3_FAN = 15
GPIO4_RIGHT = 16
GPIO5_FAR = 18
GPIO6_LEFT = 22

GPIO.setup(GPIO2_FLOW_METER, GPIO.IN)
GPIO.setup(GPIO3_FAN, GPIO.OUT)  
GPIO.setup(GPIO4_RIGHT, GPIO.OUT)
GPIO.setup(GPIO5_FAR, GPIO.OUT)
GPIO.setup(GPIO6_LEFT, GPIO.OUT)

GPIO.output(GPIO3_FAN, GPIO.HIGH)
GPIO.output(GPIO4_RIGHT, GPIO.HIGH)
GPIO.output(GPIO5_FAR, GPIO.HIGH)
GPIO.output(GPIO6_LEFT, GPIO.HIGH)

GPIO.output(GPIO3_FAN, GPIO.LOW)
GPIO.output(GPIO4_RIGHT, GPIO.LOW)
GPIO.output(GPIO5_FAR, GPIO.LOW)
GPIO.output(GPIO6_LEFT, GPIO.LOW)