import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BCM)  # GPIO Numbers instead of board numbers

RELAY_2_CAUDALIMETER = 2
RELAY_3_FAN = 3
RELAY_4_LEFT = 4
RELAY_5_FAR = 5
RELAY_6_RIGHT = 6
GPIO.setup(RELAY_2_CAUDALIMETER, GPIO.IN)  # GPIO Assign mode
GPIO.setup(RELAY_3_FAN, GPIO.OUT)  # GPIO Assign mode
GPIO.setup(RELAY_4_LEFT, GPIO.OUT)  # GPIO Assign mode
GPIO.setup(RELAY_5_FAR, GPIO.OUT)  # GPIO Assign mode
GPIO.setup(RELAY_6_RIGHT, GPIO.OUT)  # GPIO Assign mode

GPIO.output(RELAY_3_FAN, GPIO.HIGH)
GPIO.output(RELAY_4_LEFT, GPIO.HIGH)
GPIO.output(RELAY_5_FAR, GPIO.HIGH)
GPIO.output(RELAY_6_RIGHT, GPIO.HIGH)

GPIO.output(RELAY_3_FAN, GPIO.LOW)
GPIO.output(RELAY_4_LEFT, GPIO.LOW)
GPIO.output(RELAY_5_FAR, GPIO.LOW)
GPIO.output(RELAY_6_RIGHT, GPIO.LOW)